### ISSUE TITLE
SoftBody wiki page missing

### ISSUE THREAD

**Issue by Ali-RS** [davidB/sandbox_wiki_jme#3]
Hi David
it seems the "SoftBody" page is missing.
http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:softbody

**Comment by davidB** [comment]
The page doesn't exist in the archives, I've got.

**Comment by davidB** [comment]
I received a more uptodate backup with softbody.
The work continue

**Comment by Dokthar** [comment]
Thanks :) .  i can't remember if this is the last version of the page, but at least it isn't the first version. Looks good to me. Keep in mind this page is wip.

**Comment by Ali-RS** [comment]
Thanks.
